# Generated by Django 4.2.5 on 2024-02-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=254)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=1000)),
                ("mobile", models.CharField(max_length=255)),
            ],
        ),
    ]
