# Generated by Django 4.2.5 on 2024-02-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("course_amount", models.CharField(max_length=50)),
                ("dateofpurchase", models.DateField()),
                ("dateofexpiry", models.DateField()),
            ],
        ),
    ]
