# Generated by Django 4.2.5 on 2024-02-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0003_course_course_instructor"),
    ]

    operations = [
        migrations.CreateModel(
            name="courseInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("course_Img", models.URLField()),
                ("course_duration", models.CharField(max_length=255)),
                ("course_instructor", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("course_amount", models.CharField(max_length=50)),
            ],
        ),
    ]
