# Generated by Django 4.2.5 on 2024-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0004_courseinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseinfo",
            name="course_Img",
            field=models.URLField(max_length=2000),
        ),
    ]
