# Generated by Django 4.2.5 on 2024-02-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0005_alter_courseinfo_course_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="user",),
    ]
