# Generated by Django 4.2.5 on 2024-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0006_remove_course_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("course_instructor", models.CharField(max_length=255)),
                ("course_name", models.CharField(max_length=255)),
                ("course_amount", models.CharField(max_length=50)),
                ("dateofpurchase", models.DateField()),
                ("dateofexpiry", models.DateField()),
            ],
        ),
        migrations.DeleteModel(name="course",),
    ]
