# Generated by Django 4.2.5 on 2024-02-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0007_payment_delete_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="userdetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=254)),
                ("lastname", models.CharField(max_length=254)),
                ("email", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=1000)),
                ("mobile", models.CharField(max_length=255)),
                ("profession", models.CharField(max_length=255)),
                ("img", models.URLField(max_length=255)),
            ],
        ),
    ]
